### ISSUE TITLE
Unable to get it work 

### ISSUE THREAD

**Issue by kaklik** [bitwisetech/ysimi#2]
Hi, I want to use yasimi, to tune my YASim models, but I am not able to get into work. 

If I run the bokeh server I get the following `No columns to parse from file` error: 

    $ bokeh serve ysimi.py
    2022-01-19 19:51:04,555 Starting Bokeh server version 2.1.1 (running on Tornado 5.1.1)
    2022-01-19 19:51:04,555 User authentication hooks NOT provided (default user enabled)
    2022-01-19 19:51:04,556 Bokeh app running at: http://localhost:5006/ysimi
    2022-01-19 19:51:04,557 Starting Bokeh server with process id: 24022
    # 1378  HS: -4.46 deg  ApElv: -0.383  CG  34% MC   15% WB  WngInc:9.4d 67.4% St @ 14.0d 
    2022-01-19 19:51:11,471 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7f605473c490>: No columns to parse from file
    File "parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__:
     Traceback (most recent call last):
      File "/home/kaklik/.local/lib/python3.8/site-packages/bokeh/application/handlers/code_runner.py", line 197, in run
        exec(self._code, module.__dict__)
      File "/home/kaklik/repos/TF/ysimi/ysimi.py", line 1078, in <module>
        lvsdDfrm  = pd.read_csv(lvsdFid, sep='\t')
      File "/home/kaklik/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 605, in read_csv
        return _read(filepath_or_buffer, kwds)
      File "/home/kaklik/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 457, in _read
        parser = TextFileReader(filepath_or_buffer, **kwds)
      File "/home/kaklik/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 814, in __init__
        self._engine = self._make_engine(self.engine)
      File "/home/kaklik/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
        return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
      File "/home/kaklik/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1893, in __init__
        self._reader = parsers.TextReader(self.handles.handle, **kwds)
      File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
    pandas.errors.EmptyDataError: No columns to parse from file
     
    2022-01-19 19:51:11,588 WebSocket connection opened
    2022-01-19 19:51:11,589 ServerConnection created

**Comment by bitwisetech** [comment]
Hello, kaklik 

 Thank you for your interest and for trying the app.  

 I will investigate now, my first thought is,  the "sep"  should be  "delimiter"   to indicate the separator character between columns. It's possible, too, the app expects higher resolution from flightgear's yasim,  that's the purpose of the  c++ file. 

  I thought I'd pushed the "delimiter" fix yesterday, I shall check and correct if necessary. 

 Thanks again,  Best !

**Comment by bitwisetech** [comment]
Checking,  I think the file with the proper "delimiter"  is here on github,  uploaded yesterday. 

 By way of explanantion,  at ysimi.py #1117 and following, the app  expects a three column  lift / drag / LvsD
for which the flightgear/src/FDM/YASim/yasim-test.c  should be replaced with the source file you find here. 
  The updated file supplies the missing Lift-vs-Drag column and also produces plotting files with better resolution so that noise in the plots is much reduced  ( ref  [https://sourceforge.net/p/flightgear/codetickets/2629/](url) 

 If you prefer to leave flightgear source untouched then change the if(1) so that only a two-column file is expected. 

 Thanks !

**Comment by kaklik** [comment]
Thanks for the fast answer! :)
Do I understand correctly that there exists an incompatibility between the current FlightGear source code and the current code of YSIMI? 

The fast workaround is therefore either modify [the YSIMI code](https://github.com/bitwisetech/ysimi/blob/32c89ddc14ea5a823da4a2c31ac6bed8e14bea2d/ysimi.py#L1119) or patch the FG's YASim by modified [yasim-test.cpp](https://github.com/bitwisetech/ysimi/blob/main/yasim-test.cpp)?

Does accepting [the FG Ticket](https://sourceforge.net/p/flightgear/codetickets/2629/) as a pull-request to FlightGear resolve the issue?

**Comment by bitwisetech** [comment]
Yes to both of the first two questions,  don't know on the third. 
I can very quickly push to this application the one-line change so that it works with the current  flightgear source, only one of the graphs will be missing.  Then I can pursue getting the change to flightgear independently.   Does that work for you ? 

 On the rotor questions, my knowlege if the YASim internals is limited, I have only scanned the code looking at tailgear wheel-ground interactions.

**Comment by kaklik** [comment]
> Yes to both of the first two questions, don't know on the third. I can very quickly push to this application the one-line change so that it works with the current flightgear source, only one of the graphs will be missing. Then I can pursue getting the change to flightgear independently. Does that work for you ?

I tested the " if(1) change to if(0)" you had proposed in the previous post. But unfortunately, it does not have any effect on the error message, in my case. 
I think the best solution could be a modification of ysimi.py to handle both old and a "new" YASim output.  It could be very useful, because there will be many more users with the old yasim-test.cpp code in their FlightGear.  ~~The second parallel path is to make a pull request (or merge request in SF terminology). To accept modified yasim-test.cpp into standard FlightGear codebase. But this could be a relatively long-lasting attempt. I could make the pull request instead of you, if it helps you.~~  -  merged. 

> 
> On the rotor questions, my knowlege if the YASim internals is limited, I have only scanned the code looking at tailgear wheel-ground interactions.

It is interesting, we are looking for someone capable to do the development or bug fixing of YASim. The wheel-ground interaction is one of the persistent bugs in the YASim. There is even seems to be [an existing improvement](https://sourceforge.net/p/flightgear/codetickets/1509/), but there is little care, of YASim's maintenance.  I think that could be solved by the separation of YASim to isolated binary, like JSBsim.

**Comment by kaklik** [comment]
I noticed that [the FG Ticket](https://sourceforge.net/p/flightgear/codetickets/2629/) has been [merged to FG already](https://sourceforge.net/p/flightgear/flightgear/ci/4b7ef90b312f0c5a5d28cc3f603d95c975577a17/).  I am using the [flightgear-edge PPA repository](https://launchpad.net/~saiarcot895/+archive/ubuntu/flightgear-edge). Therefore I expect that it contains the modification for three-column lift/drag/LvsD.

But the error message is still the same. The cause of the error is probably different from the simple absence of the correct version of YASim.

Recently I found that files ysimi-vCurr-iasa.txt, ysimi-vCurr-lvsd.txt, and ysimi-vCurr-soln.txt are blank. I do not know why, because the `yasim ysimi-yasim-inpt.xml  -test` gives expected lift/drag/LvsD output. 

    #-- lift, drag at altitude 5000 meters, 100 knots, Config 0 --
    aoa	Lift	Drag	LvsD
    -5	-0.3455	-0.0367	9.4017
    -4	-0.1895	-0.0404	4.6954
    -3	-0.0333	-0.0423	0.7881
    -2	0.1230	-0.0425	-2.8961
    -1	0.2792	-0.0410	-6.8151
     0	0.4351	-0.0378	-11.5176

**Comment by bitwisetech** [comment]
Is it possible for you to rebuild flightgear using the supplied yasim-test.cpp, please ?   
Locally I have been using that version for a long time.  It ought to give you mmor entries in the output file so that  the graphs are useful.  
  Thanks

**Comment by kaklik** [comment]
> Is it possible for you to rebuild flightgear using the supplied yasim-test.cpp, please ? Locally I have been using that version for a long time. It ought to give you mmor entries in the output file so that the graphs are useful. Thanks

Ok, I compiled FlightGear with the modified [yasim-test.cpp](https://github.com/bitwisetech/ysimi/blob/main/yasim-test.cpp). The [diff is here](https://github.com/ThunderFly-aerospace/FlightGear/commit/d0c05b46b50f3e65d6b179a66d1f25e3284347ee). 

Then I hardcoded the YASim path to the compiled executable on [multiple lines of ysimi.py code](https://github.com/ThunderFly-aerospace/ysimi/commit/02bf4133445eb2270d280374958f4ec62abe15ad). 

After that I finally get it to work: 

![image](https://user-images.githubusercontent.com/1194177/150506717-f767e7e5-cc42-4c9e-8cb8-84fa9438c122.png)

 The issue is therefore in some changes of yasim-test.cpp, which are not merged to upstream FlightGear code.

**Comment by bitwisetech** [comment]
I thought the matter was covered in the README.  The improvements to yasim-test
were included here because the original ticket on yasim-test was apparently fixed without notification so apparently ignored,  it was pointless to propose  further changes. 
 
 Hard coding a pth to yasim executable should not be necessary, what OS are you using please ?   After flightgear is installed then yasim should execute from a command rompt, the same as 'fgfs'

**Comment by kaklik** [comment]
> I thought the matter was covered in the README. The improvements to yasim-test were included here because the original ticket on yasim-test was apparently fixed without notification so apparently ignored, it was pointless to propose further changes.

Ok, it seems to be the right time, to propose additional changes now. :)

> 
> Hard coding a pth to yasim executable should not be necessary, what OS are you using please ? After flightgear is installed then yasim should execute from a command rompt, the same as 'fgfs'

I am using Ubuntu 20.04. The change of path to correct binary was really needed until the change I get the same error as is described in the introduction of this issue.  I have FlightGear packages from PPA intalled at the same time. But I think it does not affect on selection path of binary executed by ysimi.

**Comment by bitwisetech** [comment]
Well, thanks for the direction.

**Comment by bitwisetech** [comment]
This update includes the changes needed upstream in FlightGear's yasim-test, the ticket as written had a side effect of making a mismatch on the plotting data's title lines. 

Uploaded yasim-test.cpp  and  ysimi.py : 

On Windows systems the app is compatible with patched or unpatched Flightgear, uses low-res
Running this app on linux assumes Flightgear is patched with the supplied yasim-test.cpp,  uses deteiled hi-res plots

**Comment by kaklik** [comment]
> This update includes the changes needed upstream in FlightGear's yasim-test, the ticket as written had a side effect of making a mismatch on the plotting data's title lines.
> 
> Uploaded yasim-test.cpp and ysimi.py :
> 
> On Windows systems the app is compatible with patched or unpatched Flightgear, uses low-res Running this app on linux assumes Flightgear is patched with the supplied yasim-test.cpp, uses deteiled hi-res plots

Thanks for the update!  Do I understand correctly that [your last commit](https://github.com/bitwisetech/ysimi/commit/255b2e2b7b07fcd9f9ae056692e55f82cf6e846e), contains changes needed to make in the [FlightGear next branch](https://sourceforge.net/p/flightgear/flightgear/ci/next/tree/) to be able to use ysimi?

**Comment by bitwisetech** [comment]
FlightGear 'next'  must be patched with the suplied yasim-test.cpp  until  'next' accepts the patch,   if running on Linux.  If this is a problem for your workflow please let me know:  
the fix inside this app is trivial, near #1120 are defined the case-sensitive titles for the plotting data.  
  Regarding execution paths,  I have always built FlightGear from source.  It looks as if installing FlighGear another way results in a different environment.  I've aleady noted that issue for a Windows install, I will find out if a PPA install on Linux is similar.
